set prompt="%~ %# "
bindkey -v
alias ls "ls --color"
alias l "ls -lh"
alias cls "clear"
alias vi "vim"
alias vim "vim -p"
alias gvim "gvim -p"


set path =  ( \
                $path \
                /usr/local/cuda-5.0/bin \
            )
