set prompt="%~ %# "
set history = 5000
set savehist = (5000 merge)
set histfile="$HOME/.tcsh_history"
history -L

set path =  ( \
                $path \
                /home/vdhar/bin \
                /usr/local/cuda-5.0/bin \
            )
setenv MANPAGER less

# vi like key mapping
bindkey -v

# Make command history (arrow keys) use history search operations
bindkey -k down history-search-forward
bindkey -k up history-search-backward

alias rm "rm -i"
alias ls "ls --color"
alias l "ls -lh"
alias cls "clear"
alias vi "vim -p"
alias vim "vim -p"
alias gvim "gvim -p"

#setenv DISPLAY ":0"

#print our ip address on login
#ip -o  -f inet addr

if ( ! ($?DISPLAY) ) then
    echo Setting \$DISPLAY to :0.0 since it is undefined
    setenv DISPLAY :0.0
endif
