set prompt="%~ %# "
set history = 5000
set savehist = (5000 merge)
set histfile="$HOME/.tcsh_history"
history -L

# vi like key mapping
bindkey -v

# Make command history (arrow keys) use history search operations
bindkey -k down history-search-forward
bindkey -k up history-search-backward

setenv MANPAGER less
alias l ls -lh --color
alias ls ls --color
alias cls clear
alias vim vim -p

